#pragma once

#define OPCODE_M_MUL                    0x0D00
#define OPCODE_M_ROT                    0x0D01
#define OPCODE_GET_MATRIX_X_ANGLE       0x0D02
#define OPCODE_GET_MATRIX_Y_ANGLE       0x0D03
#define OPCODE_GET_MATRIX_Z_ANGLE       0x0D04
#define OPCODE_SET_MATRIX_XYZ           0x0D05
#define OPCODE_GET_MATRIX_XYZ           0x0D06
#define OPCODE_MATRIX_LOCAL_OFFSET		0x0D07
#define OPCODE_MATRIX_ROTATE			0x0D08
#define OPCODE_MATRIX_COPY  			0x0D09
#define OPCODE_MATRIX_OFFSET			0x0D0A
#define OPCODE_BONE_MATRIX			    0x0D0B
#define OPCODE_COMPONENT_MATRIX			0x0D0C
#define OPCODE_FIND_COMPONENT			0x0D0D
#define OPCODE_SET_COMPONENT_STATE		0x0D0E
#define OPCODE_SET_CAR_ALPHA      		0x0D0F
#define OPCODE_SET_ACTOR_ALPHA      	0x0D10
#define OPCODE_SET_OBJECT_ALPHA      	0x0D11
#define OPCODE_SET_CAR_COMPONENT_ALPHA  0x0D12
#define OPCODE_MATRIX_ROT_X             0x0D13
#define OPCODE_MATRIX_ROT_Y             0x0D14
#define OPCODE_MATRIX_ROT_Z             0x0D15
#define OPCODE_M_TO_Q                   0x0D16
#define OPCODE_Q_TO_M                   0x0D17
#define OPCODE_Q_ROT                    0x0D18
#define OPCODE_Q_NORM                   0x0D19
#define OPCODE_Q_MUL                    0x0D1A
#define OPCODE_ENTITY_TYPE              0x0D1B
#define OPCODE_V_NORM                   0x0D1C
#define OPCODE_M_INT                    0x0D1D
#define OPCODE_Q_INT                    0x0D1E
#define OPCODE_COMP_CHILD               0x0D1F
#define OPCODE_COMP_NEXT                0x0D20
#define OPCODE_COMP_NAME                0x0D21
#define OPCODE_COMP_LTM                 0x0D22
#define OPCODE_COMP_MODELLING           0x0D23
#define OPCODE_Q_FILL                   0x0D24
#define OPCODE_M_FILL                   0x0D25
#define OPCODE_V_FILL                   0x0D26
#define OPCODE_MEMCPY                   0x0D27
#define OPCODE_V_GET                    0x0D28
#define OPCODE_Q_GET                    0x0D29
#define OPCODE_COL_NUM_CAR              0x0D2A
#define OPCODE_COL_NUM_ACTOR            0x0D2B
#define OPCODE_COL_NUM_OBJECT           0x0D2C
#define OPCODE_GET_LOCAL_TIME           0x0D2D
#define OPCODE_THREAD_VAR_SET           0x0D2E
#define OPCODE_THREAD_VAR_GET           0x0D2F
#define OPCODE_CBONE                    0x0D30
#define OPCODE_CBONE_OFFSET             0x0D31
#define OPCODE_CBONE_QUAT               0x0D32
#define OPCODE_CAR_WINDOW               0x0D33
#define OPCODE_COL_ENT_CAR              0x0D34
#define OPCODE_COL_ENT_ACTOR            0x0D35
#define OPCODE_COL_ENT_OBJECT           0x0D36
#define OPCODE_SET_STRUCT_PARAM         0x0D37
#define OPCODE_GET_STRUCT_PARAM         0x0D38
#define OPCODE_PED_MAX_HEALTH           0x0D39
#define OPCODE_COL_POINTS               0x0D3A
#define OPCODE_COLPOINT_NORMAL          0x0D3B
#define OPCODE_COLPOINT_SURFACE         0x0D3C
#define OPCODE_COLPOINT_LIGHTING        0x0D3D
#define OPCODE_COLPOINT_DEPTH           0x0D3E
#define OPCODE_CIRCLE_INT               0x0D3F
#define OPCODE_DRAW_SHAPE               0x0D40
#define OPCODE_SET_VERTEX               0x0D41
#define OPCODE_TXD_LOAD                 0x0D42
#define OPCODE_TXD_ID                   0x0D43
#define OPCODE_TXD_FIND                 0x0D44
#define OPCODE_ROTATE_VERTICES          0x0D45
#define OPCODE_TXD_FIND2                0x0D46
#define OPCODE_MODEL_TXD                0x0D47
#define OPCODE_MODEL_CRC_KEY            0x0D48
#define OPCODE_STRCMP                   0x0D49
#define OPCODE_STRCAT                   0x0D4A
#define OPCODE_STRSTR                   0x0D4B
#define OPCODE_STRLEN                   0x0D4C
#define OPCODE_STRCPY                   0x0D4D
#define OPCODE_STRUCT_OFFSET_READ       0x0D4E
#define OPCODE_STRUCT_OFFSET_WRITE      0x0D4F
#define OPCODE_DRAW_SHADOW              0x0D50
#define OPCODE_DRAW_PERMANENT_SHADOW    0x0D51
#define OPCODE_DRAW_LIGHT               0x0D52
#define OPCODE_DRAW_CORONA              0x0D53
#define OPCODE_DRAW_CORONA_EXTRA        0x0D54
#define OPCODE_SUN_COLOR                0x0D55
#define OPCODE_SUN_2D_POS               0x0D56
#define OPCODE_SUN_3D_POS               0x0D57
#define OPCODE_SUN_SIZE                 0x0D58
#define OPCODE_GET_WEATHER              0x0D59
#define OPCODE_TRAFFLIGHT               0x0D5A
#define OPCODE_DRAW_SPOTLIGHT           0x0D5B
#define OPCODE_CARLIGHT_GET             0x0D5C
#define OPCODE_CARLIGHT_SET             0x0D5D
#define OPCODE_VEHICLE_CLASS            0x0D5E
#define OPCODE_VEHICLE_DUMMY            0x0D5F
#define OPCODE_ADD_PROJECTILE           0x0D60
#define OPCODE_TEXTURE_FROM_BITMAP      0x0D61
#define OPCODE_CAR_REMAP                0x0D62
#define OPCODE_CAR_COLOR                0x0D63
#define OPCODE_PNG                      0x0D64
#define OPCODE_PRINT_BASIC              0x0D65
#define OPCODE_PRINT                    0x0D66
#define OPCODE_SET_AUDIOSTREAM_POS      0x0D67
#define OPCODE_GET_AUDIOSTREAM_POS      0x0D68
#define OPCODE_SET_AUDIOSTREAM_EFFECT   0x0D69
#define OPCODE_REMOVE_AUDIOSTREAM_EFFECT 0x0D6A
#define OPCODE_SET_EFFECT_PARAMETERS    0x0D6B
#define OPCODE_GET_EFFECT_PARAMETERS    0x0D6C
#define OPCODE_RESET_EFFECT             0x0D6D
#define OPCODE_SET_AUDIOSTREAM_ATTR     0x0D6E
#define OPCODE_GET_AUDIOSTREAM_ATTR     0x0D6F
#define OPCODE_SET_3D_AUDIOSTREAM_ATTR  0x0D70
#define OPCODE_GET_3D_AUDIOSTREAM_ATTR  0x0D71
#define OPCODE_GET_GAME_VOLUME          0x0D72
#define OPCODE_GET_SCREEN_WH            0x0D73